
[alerts]
	arrows_alert = true
	lock_chest_alert = true
	"&fspirit_mask&r_alert" = false
	"&5phonix_pet&r_alert" = false
	bonzo_mask_alert = true
	"&dlock_&bchest_&falert" = false
	"&9bonzo_mask&r_alert" = false
	spirit_mask_alert = true
	"m7_&6ragnarock_axe&r_alert" = false
	"&cm6_&dgyro&r_alerts" = false
	"&carrows&r_alert" = false
	"&cbonzo_mask&r_alert" = false
	watcher_alerts = true
	m6_gyro_alerts = true
	phonix_pet_alert = true
	"&cwatcher&r_alerts" = false

[general]

	[general.bhl]
		thickness = 2

[mod_toggles]
	y = 50

[toggle]
	m7_dragon_box = true
	custom_fov = true
	spirit_mask_timer = false
	i_hate_carpets = true
	"&fcustom_fov" = true
	"&fspirit_mask&r_&etimer&r" = true
	scale = 200
	"&fspirit_mask&r_&ftimer&r" = false
	"&ffov" = 120
	fov = 125
	m7_dragon_spawn_timer = false
	remove_selfie_camera = false
	"&5phonix_pet&r_&ftimer&r" = false
	"&l&ci_hate_carpets" = true
	"bonzo_mask_&ftimer" = false
	"&cm7_&0dragon_box" = false
	"&5phonix_pet&r_&etimer&r" = true
	auto_refill_ender_pearls = true
	"&aremove_sword_block" = true
	"auto_&erefill_&3ender_pearls" = true
	"&5phonix_pet_&ftimer" = false
	"&cremove&r_&aselfie&f_camera" = true
	i_hate_diorite = true
	"spirit_mask_&ftimer" = false
	"&dpink&r_dms" = true
	"&dshort_&bsky&dblock_&bcommands" = true
	phonix_pet_timer = false
	"&cremove&r_selfie_camera" = true
	"&cbonzo_mask&r_&etimer&r" = true
	"&cm7_&0dragon&r_box" = true
	no_sword_block = true
	pink_dms = true
	"&l&ci_hate_diorite" = true
	x = 200
	bonzo_mask_timer = false
	y = 200
	"&9bonzo_mask&r_&ftimer&r" = false
	"&9bonzo_mask&r_&etimer&r" = false
	short_skyblock_commands = true
	"&cm7_&0dragon_spawn_&etimer" = false
	"&cm7_&0dragon&f_spawn_&etimer" = false
	"&blegit_ghost_pickaxe" = true

	[toggle.gray_zone]
		"&l&ci_hate_carpets" = true
		"&dlegit_ghost_pickaxe" = false
		i_hate_carpets = true
		no_sword_block = true
		"&l&ci_hate_diorite" = true
		remove_sword_block = false
		x = 315
		scale = 593
		y = 38
		legit_ghost_pickaxe = true
		i_hate_diorite = true
		"&blegit_ghost_pickaxe" = false

[undefined]
	undefined = 0

[sb_alerts]
	"&5phonix_pet&r_alert" = false

