
[alerts]
	"&carrows&r_alert" = true
	"§5full_thunder_bottle_alert" = true
	"&fspirit_mask&r_alert" = true
	"&9bonzo_mask&r_alert" = true
	"&5phoenix_pet&r_alert" = true

	[alerts.dungeons]
		"m7_&6ragnarock_axe&r_alert" = false
		"&cm6_&dgyro&r_alerts" = false
		"&dlock_&bchest_&falert" = true
		"&5shadow_assasian_&falert" = true
		"&cwatcher&r_alerts" = true

[general]
	waypoint_color = "255,0,145,255"
	"&achat_coords_&d2_waypoint" = false
	color = "255,0,141,255"
	"&dshort_&bsky&dblock_&bcommands" = true
	chat_coords_2_waypoint = true

	[general.timers]
		"&7p3_&fstart_&etimer" = true
		"&dp2_&fstart_&etimer" = false
		"&fspirit_mask&r_&etimer&r" = true
		"&4p5_&fstart_&etimer" = false
		"&5p1_&fstart_&etimer" = true
		"&ap2_&fstart_&etimer" = true
		"&ap4_&fstart_&etimer" = true
		"&cnecron_dropping_&etimer" = true
		"f7/m7_phase_start_timers" = true
		"&ap1_&fstart_&etimer" = true
		"&cp4_&fstart_&etimer" = true
		"&ap3_&fstart_&etimer" = true
		"&bp2_&fstart_&etimer" = true
		"&9bonzo_mask&r_&etimer&r" = true
		"&5phoenix_pet&r_&etimer&r" = true

	[general.dungeons]
		"&ateammates_&6nametag" = true
		"&adungeon_teammates_&6nametag" = true
		announced_massage = "${name} Might suffer from diabitis"
		"&c&li_hate_diorite" = false
		"§cblood_§bdialouge_§eskip" = true
		"announced_&6massage" = "I TP to ${name}"
		"&cm7_&0dragon&r_box" = false
		"&adungeon_&6team&amates_&6nametag" = false
		"&fdungeon_&emob_&de&bs&dp" = true
		"&dc&bo&dl&bo&dr" = "255,0,120,255"
		"&ddungeon_auto_extra_stats" = false
		"&l&ci_hate_diorite" = true
		"&de&bs&dp_&6mode" = 2
		"auto_&erefill_&3ender_pearls" = false
		"&de&bs&dp_&dc&bo&dl&bo&dr" = "43,0,133,255"
		blood_dialouge_skip = false
		"&ehide_&cfalling_&eblocks" = true
		"&blegit_ghost_pickaxe" = true
		"&cm7_&0dragon&f_spawn_&etimer" = false
		"&ebetter_&3ender_pearls" = true
		"announce_&fspirit_&bleaps" = true

[cosmetic]
	custom_slot_highlight = true
	slot_highlight_color = "55,222,0,255"

	[cosmetic.visuals]
		"&ecustom_&dfov" = true
		"&bfov" = 114
		color = "255,0,141,255"
		"&dpink&r_dms" = true
		spin_diraction = 0
		custom_slot_highlight = true
		slot_highlight_color = "255,0,141,255"
		spin_speed = 200
		"&aremove_sword_block" = true
		spin = false
		"&cremove&r_&aselfie&f_camera" = false

	[cosmetic.block_overlay]
		"§n&fblock_overlay" = true
		block_overlay_type = 2
		overlay_color = "87,0,255,59"
		"&6show_through_blocks?" = false
		"block_overlay_&etype" = 0
		outline_thickness = 5
		"show_through_blocks?" = true
		outline_color = "255,0,169,255"
		"show_through_other_blocks?" = false

	[cosmetic.player]
		spin_diraction = 0
		spin_speed = 50
		spin = false
		"player's_scale" = true
		custom_scale = 67

